### ISSUE TITLE
[Bitwarden] Abstract away DB-WAL setting

### ISSUE THREAD

**Issue by Ornias1993** [gissilabs/charts#10]
DB_WAL is either true for sqlite or false for actual databases.
We can easily abstract this away (certainly when custom env's get supported)

**Comment by sgissi** [comment]
DB_WAL is automatically disabled on other DBs and defaults to true for SQLite. The user does have the option to disable it if he wants to. I don't think there is more abstraction needed, what do you suggest?

**Comment by Ornias1993** [comment]
@sgissi I understood it wrong:
 `Enable DB Write-Ahead-Log for SQLite, disabled for other databases`

maybe make it:
 `Enable DB Write-Ahead-Log for SQLite, automatically disabled for other databases`
