### ISSUE TITLE
Very slow actions

### ISSUE THREAD

**Issue by pacobuenaparte** [gissilabs/charts#11]
Hi,

I've just installed Leantime with this helmchart and I notice some post requests actions take incredibly long time (like create a project for example, or edit a task which lasts 30 second). I see no error log at all nor any indication. 
I tested with both internal MariaDB or external one and the result is the same.

Can you help me understand what's going on ?

![Screenshot from 2020-09-19 10-17-34](https://user-images.githubusercontent.com/17688116/93662569-674b9600-fa61-11ea-83ef-16e6852afe25.png)

**Comment by sgissi** [comment]
Hi, I see there is an upstream bug open (https://github.com/Leantime/leantime/issues/329). I'll close this one for now to concentrate troubleshooting there.
