### ISSUE TITLE
Upgrade to 1.19.0

### ISSUE THREAD

**Issue by KeepMasterBranch** [gissilabs/charts#18]
it now use a single docker image for all variants

**Comment by sgissi** [comment]
Indeed! I have a branch working on the upgrade since 1.18 came out but didn’t finish yet. I’ll try to get it out this week, thanks for the reminder.

**Comment by sgissi** [comment]
Hi, I have updated the chart to 1.19.0. I test on my local deployment from 1.16.3 without problems. Can you check if it works well for you?

**Comment by sgissi** [comment]
@KeepMasterBranch Did you have the chance to test? I'll close the issue, feel free to reopen or comment if it doesn't work for you.
