### ISSUE TITLE
Update to 1.21.0 with the rename to vaultwarden

### ISSUE THREAD

**Issue by edgan** [gissilabs/charts#19]
dani-garcia has renamed bitwarden_rs to vaultwarden with 1.21.0. Can you update the helm chart to use the new image?

I suspect leaving the name of the helm chart would be wise. My experience with helm suggests it doesn't deal with renames well. Though even with the helm chart name not changing hopefully the upgrade path is smooth.

**Comment by sgissi** [comment]
Thanks, I did see it a few days ago. I will update my environment to test and release a new chart. I will probably release a parallel chart with the new name (same content) and keep both for some time so people can transition.

**Comment by sgissi** [comment]
@edgan I have released a new version and kept the chart name. I have also created a new vaultwarden chart. I'll keep them both for the time being (identical chart and application versions) but will eventually deprecate bitwardenrs in favor of vaultwarden. Let me know if it is working well for you.

**Comment by sgissi** [comment]
The new charts have been out for a while, closing this issue :) Let me know if it doesn't work for any reason.
