### ISSUE TITLE
Missing option from SMTP config - "Force TLS"

### ISSUE THREAD

**Issue by lord-kyron** [gissilabs/charts#20]
Hi,
as I am forced to use this option by my mail provider, I've noticed that this is missing from the chart. Every time (when I need to make a new deployment) I need to enable the admin interface and despite I have all options that I need in the chart values, I have to go and enable this particular one: Force TLS.
From official docs, I saw that:
`To run SMTP in explicit mode, set SMTP_EXPLICIT_TLS to true (SMTP_SSL has to be set to 'true', too)`
So my request here is to add support (expose this option to be configurable) in values.yaml file.
Thanks!

**Comment by sgissi** [comment]
Thanks for raising this point, indeed I missed SMTP_EXPLICIT_TLS somehow. For the moment, please set bitwardenrs.smtp.ssl to true and, under bitwardenrs.extraEnv, add "SMTP_EXPLICIT_TLS: true" as a workaround. I'll add the smtp.explicitTLS option in the next release of both bitwardenrs and vaultwarden charts.

**Comment by lord-kyron** [comment]
Thanks!

**Comment by lord-kyron** [comment]
Hi @sgissi -  since from some time version 1.22.2 is the latest, do you plan to update the chart with latest version + the option that I found missing from above?
Thanks!

**Comment by sgissi** [comment]
Thanks for the reminder, an update is overdue for sure. I'll carve out some time this weekend to update the chart and include the SMTP TLS setting too.

**Comment by sgissi** [comment]
Hi, the latest version was just released with the Explicit TLS option. Can you give it a try please?

**Comment by sgissi** [comment]
@lord-kyron I'm closing the issue as the new charts were released with the Explicit TLS option. Feel free to reopen in case of any issues. Thanks for raising the issue!
