### ISSUE TITLE
Chart does not template v1 Ingress

### ISSUE THREAD

**Issue by jonkerj** [gissilabs/charts#24]
This chart templates currently deprecated/legacy Ingress, which makes it kind of tricky to use on Kubernetes 1.22 (which has dropped v1beta1 ingress). I've written a PR (#23) to address this, this is the matching issue.

**Comment by sgissi** [comment]
Thanks for raising the issue and proposing the PR! I added a few comments there, please take a look and then we are ready to merge. Thanks again!

**Comment by sgissi** [comment]
Thank you again, the changes are merged and should be published this weekend.

**Comment by jonkerj** [comment]
Raised #25 as well. Should have done it at once :-)

**Comment by sgissi** [comment]
That was really fast! :) Thank you very much, the PR is merged.

**Comment by sgissi** [comment]
Hi, I just released the charts with your changes, can you give it a try please? Thanks for the contribution!

**Comment by jonkerj** [comment]
It works, thanks!
