### ISSUE TITLE
Update Vaultwarden to 1.23

### ISSUE THREAD

**Issue by sgissi** [gissilabs/charts#26]
New Emergency Access feature implemented.

**Comment by pixelfields** [comment]
Hi @sgissi , 

any updates on this? Very probably we hit https://github.com/dani-garcia/vaultwarden/issues/1920 issue, and upgrade to 1.23 could be a solution (not guaranteed, though). 

My plan is to test a simple upgrade with changing the `image.tag`. Do you think, would it be enough?

**Comment by pixelfields** [comment]
Thanks for the info! I've upgraded to `1.23.0` directly with changing `image.tag`, and all went smoothly.
