### ISSUE TITLE
Update Vaultwarden to 1.24

### ISSUE THREAD

**Issue by themightychris** [gissilabs/charts#31]
Here's the release: https://github.com/dani-garcia/vaultwarden/releases/tag/1.24.0

Is there anything in there warranting more than just bumping `appVersion`?

**Comment by sgissi** [comment]
@themightychris Thanks for raising this, I don't think it needs much more than a bump, I'll give feedback on #32.

In the meantime, you can set image.tag to "1.24.0" if you want to upgrade to the latest. As with any upgrade, make sure to have a backup and, if possible, upgrade a non-production deployment first.
