### ISSUE TITLE
[Feature] [Bitwarden] Custom env vars option

### ISSUE THREAD

**Issue by Ornias1993** [gissilabs/charts#4]
For future proofing it might be interesting to at least add the option to include additional custom env-vars that are not pre-defined into the values.yaml file.

A bit of what this version of helm-for-bitwarden_rs does, but while keeping your amazing list of config options:
https://github.com/cdwv/bitwarden-k8s

**Comment by sgissi** [comment]
Thanks for the feedback, this should be fairly straightforward. I'll try to arrange time near end of the week.
