### ISSUE TITLE
Update Vaultwarden to 1.29.0

### ISSUE THREAD

**Issue by SerhiiK** [gissilabs/charts#49]
Here's the release: https://github.com/dani-garcia/vaultwarden/releases/tag/1.29.0

**Comment by akelge** [comment]
Meanwhile dani garcia released 1.30.1: https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.1

Any hope to have this updated?

**Comment by sgissi** [comment]
Hi all, sorry for the long delay. I'm working on updating the chart to latest (1.30.5).

**Comment by sgissi** [comment]
Chart is updated to 1.30.5, working fine on my environment. Please open an issue if you have problems.
