### ISSUE TITLE
[Feature] [Bitwarden] Add middleware option to Traefik Ingressroute

### ISSUE THREAD

**Issue by Ornias1993** [gissilabs/charts#5]
A lot of people use custom middlewares for Traefik Ingressroute, for example to enforce certain security settings or set additional headers. Adding this as an option should be relatively easy.

**Comment by sgissi** [comment]
Thanks for the feedback, I'll take a look. Feel free to propose a PR if you already know how to implement.

**Comment by Ornias1993** [comment]
@sgissi I might take a crack at it if I can find the time. Should be basically the same as how TLS is handled now I think 👍
