### ISSUE TITLE
[Bitwarden] [Feature] Add backup of persistant data

### ISSUE THREAD

**Issue by Ornias1993** [gissilabs/charts#9]
Sometime persistant data goes wrong and some people prefered having a backup on the same persistant volume.

Skeen has a nice solution for this, which is relatively easy to use:
https://github.com/Skeen/helm-bitwarden_rs/blob/master/charts/bitwarden/values.yaml

**Comment by sgissi** [comment]
The idea of the chart is to expose the upstream features into a K8S deployment. I would not add a separate scheduler for backup unless it was officially supported by the upstream project.

**Comment by Ornias1993** [comment]
@sgissi It is supported, the implementation like SKEEN does just copies the persistant data as a way of providing a backup. Which is certainly supported with sqlite and such.

**Comment by sgissi** [comment]
Coming back to this lingering issue. I'll add a generic sidecar support, with this the users can choose an image that suits them to access the data.

**Comment by Ornias1993** [comment]
Awesome :)

**Comment by sgissi** [comment]
And finally, generic sidecar is now supported on all charts. Please reopen if you have issues using it.
